name: 'Rust Release and Build'
description: 'Reusable action for Rust release and build process'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  changelog_path:
    description: 'Path to the changelog file'
    default: 'CHANGELOG.md'
    required: false
  release_prefix:
    description: 'Prefix for release branches'
    default: 'release-'
    required: false
  targets:
    description: 'JSON string of Rust build targets'
    required: true
  packages:
    description: 'JSON string of Rust packages to build'
    required: true
  pre_release:
    description: 'Indicates if the release is a pre-release'
    required: false
    default: 'false'
  action:
    description: 'Action to perform (pre-release, release, cleanup)'
    required: true
outputs:
  version:
    description: 'Extracted version number from the branch name'
runs:
  using: "composite"
  steps:
    - name: Set up Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
      shell: bash

    - name: Generate changelog and version
      id: cliff
      if: inputs.action == 'pre-release' || inputs.action == 'release'
      uses: orhun/git-cliff-action@v3
      with:
        config: Cargo.toml
        args: --bump --github-repo ${{ github.repository }}
      env:
        OUTPUT: ${{ inputs.changelog_path }}
        GITHUB_REPO: ${{ github.repository }}

    - name: Extract version from changelog
      id: extract_version
      if: inputs.action == 'pre-release' || inputs.action == 'release'
      run: |
        VERSION=$(grep -oP '(?<=## \[)\d+\.\d+\.\d+' ${{ inputs.changelog_path }} | head -n 1)
        if [ -z "${VERSION}" ]; then
          echo "Version not found in changelog"
          exit 1
        fi
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=version::$VERSION"
      shell: bash

    - name: Create or update release
      if: inputs.action == 'pre-release' || inputs.action == 'release'
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
        VERSION: ${{ env.VERSION }}
      run: |
        NOTES=$(sed -n '/## \['${VERSION}'\]/,/## \[/p' ${{ inputs.changelog_path }} | sed '$d' | sed '1d')
        if [ "${{ inputs.pre_release }}" == "true" ]; then
          gh release create "${VERSION}" --title "${VERSION}" --notes "${NOTES}" --prerelease
          git checkout -b release-next
          git commit --allow-empty -m "chore(release): prepare for release ${VERSION}"
          git push origin release-next
          gh pr create --title "Release ${VERSION}" --body "Pre-release ${VERSION}" --base main --head release-next
        else
          gh release create "${VERSION}" --title "${VERSION}" --notes "${NOTES}"
        fi
      shell: bash

    - name: Process targets and packages
      if: inputs.action == 'pre-release' || inputs.action == 'release'
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
        VERSION: ${{ env.VERSION }}
      run: |
        targets=$(echo '${{ inputs.targets }}' | jq -r '.[]')
        packages=$(echo '${{ inputs.packages }}' | jq -r '.[]')
        for target in $targets; do
          rustup target add $target
          for package in $packages; do
            cargo build --release --target $target --package $package
            mv target/$target/release/$package "${package}_${target}_${VERSION}"
            gh release upload "${VERSION}" "${package}_${target}_${VERSION}" --clobber
          done
        done
      shell: bash

    - name: Clean up chore(release) commits
      if: inputs.action == 'cleanup'
      run: |
        commits=$(git log --pretty=format:"%H" --grep "chore(release): release")
        if [ -n "$commits" ]; then
          git rebase --onto $(echo "$commits" | tail -1)^ --no-ff $(echo "$commits" | head -1)^
        fi
      shell: bash
