# .github/workflows/create-pre-release.yml
name: Create Pre-release

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create_pre_release:
    if: github.event.pull_request.merged == true && !startsWith(github.event.pull_request.head.ref, 'release-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install git-cliff
        run: cargo install git-cliff

      - name: Generate changelog
        run: git cliff --output CHANGELOG.md

      - name: Create pre-release
        id: create_pre_release
        uses: softprops/action-gh-release@v1
        with:
          files: CHANGELOG.md
          draft: false
          prerelease: true
          tag_name: v${{ github.sha }}
          name: "Pre-release ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
