name: Rust Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure-cicd.yml'
      - 'DockerFile'

jobs:
  rust-release:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'release-v') &&
      contains(github.event.pull_request.head.ref, '.')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: Use Rust Release and Build action
        uses: ./.github/actions/rust_release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_path: 'CHANGELOG.md'
          release_prefix: 'release-v'
          targets: 
            - x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu
          packages: 
            -test-ci
          pre_release: 'true'
  