name: Rust CI Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'infrastructure/**'
      - '.github/workflows/infrastructure-cicd.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Generate a changelog
      id: cliff
      uses: orhun/git-cliff-action@v3
      env:
        OUTPUT: CHANGELOG.md
        GITHUB_REPO: ${{ github.repository }}
    
    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
    
    - name: Create Release Branch 
      run: |
        VERSION=$(echo "${{ steps.cliff.outputs.version }}")
        BRANCH="release-${VERSION}"
        git checkout -b ${BRANCH}
        git push --set-upstream origin ${BRANCH}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Create Pull Request
      run: |
        VERSION=$(echo "${{ steps.cliff.outputs.version }}")
        BRANCH="release-${VERSION}"
        git push --set-upstream origin ${BRANCH}
        git checkout ${BRANCH}
        VERSION=$(echo "${{ steps.version.outputs.version }}")
        gh pr create --title "Release version ${VERSION}" --body "Automated release of version ${VERSION}" --base main --head "release-${VERSION}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    